version: '2'
services:
  mi-mysql:
    image: mysql
    container_name: mi-mysql
    networks:
      mi-red:
         ipv4_address: 172.27.0.15
    environment:
      - MYSQL_ROOT_PASSWORD=toor
    volumes:
      - mi-volumen:/var/lib/mysql
    restart: always

  mi-dashboard:
    image: phpmyadmin
    container_name: mi-dashboard
    networks:
      mi-red:
         ipv4_address: 172.27.0.16
    environment:
      - PMA_HOST=mi-mysql
    ports:
      - 8080:80
    restart: always

    depends_on:
      - mi-mysql

networks:
   mi-red:
        ipam:
            driver: default
            config:
              - subnet: 172.27.0.0/16

    
volumes:
  mi-volumen: